# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - healthcare-iot-wa
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '24.x'

      - name: Install dependencies and build frontend
        run: |
          npm install --prefix frontend
          npm run build --prefix frontend
        env:
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL }}
          VITE_CLIENT_ID: ${{ secrets.VITE_CLIENT_ID }}
          VITE_TENANT_ID: ${{ secrets.VITE_TENANT_ID }}
          VITE_API_ID: ${{ secrets.VITE_API_ID }}

      - name: Deploy React frontend to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'healthcare-iot-wa'
          slot-name: 'Production'
          package: ./frontend/dist
          clean: true
          publish-profile: ${{ secrets.AZURE_APPSERVICES_PUBLISHPROFILE_WA }}
